spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:database
  sql:
    init:
      mode: always
      schema-locations: classpath:db/dev/schema.sql
      data-locations: classpath:db/dev/data.sql
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
  flyway:
    enabled: false

  config:
    activate:
      on-profile: dev
