name: Dev server CD

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  cd:
    runs-on: [self-hosted, dev]
    steps:
      - name: Grant execute permission to deploy.sh
        run: chmod +x home/ubuntu/deploy.sh

      - name: Start Deploy Script
        run: /home/ubuntu/deploy.sh
